# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'huiyan' do
pod 'AFNetworking’,’~>3.1.0’
pod 'SDWebImage’,’~>3.7.5’
pod 'MJRefresh’,’~>3.1.0’
pod 'Masonry’,’~>1.0.0’
pod 'RealReachability’,’~>1.1.3’
pod 'AMapSearch’,’~> 3.3.0’
pod 'AMapLocation’,’~> 1.2.2'
pod 'AMap2DMap’,’~> 3.3.0’
pod 'RongCloudIMKit’,’~> 2.5.0'
pod 'TSMessagesNW’,’~> 0.9.15'
pod 'SVProgressHUD’,’~> 2.0.3'
end

target 'huiyanTests' do

end

target 'huiyanUITests' do

end

